version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  mern-app:
    image: ranou98/mern-rania-elhor  # Specify the image name from Docker Hub
    container_name: mern-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
